package com.gonthera.cli.service.node;

import com.google.gson.GsonBuilder;
import com.gonthera.cli.model.Endpoints;
import com.gonthera.cli.model.Entities;
import com.gonthera.cli.model.EntityFields;
import com.gonthera.cli.model.Enums;
import com.gonthera.cli.model.Parameters;
import com.gonthera.cli.model.Properties;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static com.gonthera.cli.service.common.Common.loadWxsd;
import static com.gonthera.cli.service.node.NodeCommon.className;
import static com.gonthera.cli.service.node.NodeCommon.primaryKey;

public final class GenerateOpenApi {

    private static final String VERSION = "2.1.3";

    private GenerateOpenApi() {
    }

    public static void generate(Properties project, Path packagePath) {
        try {
            String json = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create()
                    .toJson(document(project));
            NodeCommon.writeFile(packagePath.resolve("documentation/openapi.ts"),
                    loadWxsd("openapi").replace("<<document>>", json));
        } catch (IOException ex) {
            throw new UncheckedIOException("Unable to generate Node OpenAPI document", ex);
        }
    }

    private static Map<String, Object> document(Properties project) {
        Map<String, Object> document = object();
        document.put("openapi", "3.0.3");
        document.put("info", map(
                "title", project.getProjectName(),
                "version", VERSION,
                "description", "OpenAPI generated by Gonthera CLI from .gonthera metadata."
        ));
        document.put("servers", List.of(map("url", "/")));

        List<Map<String, Object>> tags = new ArrayList<>();
        project.getEntities().stream()
                .filter(entity -> !entity.isOnlyDTO() && entity.isGenerateDefaultControllers())
                .forEach(entity -> tags.add(map(
                        "name", className(entity.getEntityName()),
                        "description", description(entity.getComment(), "CRUD de " + entity.getEntityName())
                )));
        project.getEndpoints().stream()
                .map(GenerateOpenApi::endpointTag)
                .distinct()
                .forEach(tag -> tags.add(map("name", tag)));
        document.put("tags", tags);

        Map<String, Object> paths = object();
        project.getEntities().stream()
                .filter(entity -> !entity.isOnlyDTO() && entity.isGenerateDefaultControllers())
                .forEach(entity -> addCrudPaths(paths, entity, project));
        project.getEndpoints().forEach(endpoint -> addEndpointPath(paths, endpoint, project));
        document.put("paths", paths);
        document.put("components", map("schemas", schemas(project)));
        return document;
    }

    private static Map<String, Object> schemas(Properties project) {
        Map<String, Object> schemas = object();
        schemas.put("Error", map(
                "type", "object",
                "required", List.of("error"),
                "properties", map("error", map(
                        "type", "object",
                        "required", List.of("code", "message"),
                        "properties", map("code", map("type", "string"), "message", map("type", "string"))
                ))
        ));

        for (Enums enumeration : project.getEnums()) {
            schemas.put(className(enumeration.getEnumName()), map(
                    "type", "string",
                    "enum", enumeration.getValues()
            ));
        }
        for (Entities entity : project.getEntities()) {
            String name = className(entity.getEntityName());
            schemas.put(name, entityOutput(entity, project));
            schemas.put(name + "Create", entityInput(entity, project, false));
            schemas.put(name + "Update", entityInput(entity, project, true));
            schemas.put(name + "Reference", entityReference(entity, project));
            schemas.put(name + "Page", page(name));
        }
        for (Endpoints endpoint : project.getEndpoints()) {
            String name = className(endpoint.getMethodName());
            schemas.put(name + "Input", parametersSchema(endpoint.getMetadata().getInput(), project));
            schemas.put(name + "Output", parametersSchema(endpoint.getMetadata().getOutput(), project));
        }
        return schemas;
    }

    private static Map<String, Object> entityOutput(Entities entity, Properties project) {
        Map<String, Object> properties = object();
        for (EntityFields field : entity.getEntityFields()) {
            Map<String, Object> schema = nullable(fieldSchema(field, project, InputMode.OUTPUT));
            addDescription(schema, field.getComment());
            properties.put(field.getFieldName(), schema);
        }
        return map("type", "object", "properties", properties);
    }

    private static Map<String, Object> entityInput(Entities entity, Properties project, boolean update) {
        Map<String, Object> properties = object();
        List<String> required = new ArrayList<>();
        EntityFields key = primaryKey(entity);
        for (EntityFields field : entity.getEntityFields()) {
            if (field == key && (update || autoGeneratedKey(field))) continue;
            Map<String, Object> schema = fieldSchema(field, project, update ? InputMode.UPDATE : InputMode.CREATE);
            addDescription(schema, field.getComment());
            properties.put(field.getFieldName(), schema);
            if (!update && requiredOnCreate(field, key)) required.add(field.getFieldName());
        }
        Map<String, Object> schema = map("type", "object", "properties", properties);
        if (!required.isEmpty()) schema.put("required", required);
        return schema;
    }

    private static Map<String, Object> entityReference(Entities entity, Properties project) {
        EntityFields key = primaryKey(entity);
        Map<String, Object> keySchema = fieldSchema(key, project, InputMode.REFERENCE);
        addDescription(keySchema, key.getComment());
        return map(
                "type", "object",
                "required", List.of(key.getFieldName()),
                "properties", map(key.getFieldName(), keySchema)
        );
    }

    private static Map<String, Object> page(String entityName) {
        return map(
                "type", "object",
                "required", List.of("size", "offset", "total", "contents"),
                "properties", map(
                        "size", map("type", "integer", "format", "int32"),
                        "offset", map("type", "integer", "format", "int32", "description", "Índice de página baseado em zero na resposta."),
                        "total", map("type", "integer", "format", "int64"),
                        "contents", map("type", "array", "items", ref(entityName))
                )
        );
    }

    private static Map<String, Object> parametersSchema(List<Parameters> parameters, Properties project) {
        Map<String, Object> properties = object();
        List<String> required = new ArrayList<>();
        for (Parameters parameter : parameters) {
            properties.put(parameter.getParameterName(), parameterSchema(parameter, project));
            required.add(parameter.getParameterName());
        }
        Map<String, Object> schema = map("type", "object", "properties", properties);
        if (!required.isEmpty()) schema.put("required", required);
        return schema;
    }

    private static void addCrudPaths(Map<String, Object> paths, Entities entity, Properties project) {
        String route = "/" + NodeCommon.varName(entity.getEntityName());
        String name = className(entity.getEntityName());
        String tag = name;
        Map<String, Object> collection = object();
        collection.put("get", map(
                "tags", List.of(tag),
                "summary", "Listar " + entity.getEntityName(),
                "operationId", "list" + name,
                "parameters", listParameters(),
                "responses", responses("200", "Registros encontrados", ref(name + "Page"), false, false)
        ));
        collection.put("post", map(
                "tags", List.of(tag),
                "summary", "Criar " + entity.getEntityName(),
                "operationId", "create" + name,
                "requestBody", requestBody(ref(name + "Create")),
                "responses", responses("200", "Registro criado", ref(name), true, true)
        ));
        paths.put(route, collection);

        Map<String, Object> item = object();
        item.put("parameters", List.of(map(
                "name", "id", "in", "path", "required", true,
                "description", "Valor da chave primária configurada para a entidade.",
                "schema", fieldSchema(primaryKey(entity), project, InputMode.REFERENCE)
        )));
        item.put("get", map(
                "tags", List.of(tag), "summary", "Consultar " + entity.getEntityName(),
                "operationId", "get" + name,
                "parameters", List.of(displayFields()),
                "responses", responses("200", "Registro encontrado", ref(name), true, false)
        ));
        item.put("put", map(
                "tags", List.of(tag), "summary", "Atualizar " + entity.getEntityName(),
                "operationId", "update" + name,
                "requestBody", requestBody(ref(name + "Update")),
                "responses", responses("200", "Registro atualizado", ref(name), true, true)
        ));
        item.put("delete", map(
                "tags", List.of(tag), "summary", "Excluir " + entity.getEntityName(),
                "operationId", "delete" + name,
                "responses", responses("204", "Registro excluído", null, true, true)
        ));
        paths.put(route + "/{id}", item);
    }

    private static void addEndpointPath(Map<String, Object> paths, Endpoints endpoint, Properties project) {
        String path = "/" + endpoint.getMethodName();
        String method = endpoint.getHttpMethod().toLowerCase();
        String name = className(endpoint.getMethodName());
        Map<String, Object> operation = map(
                "tags", List.of(endpointTag(endpoint)),
                "summary", description(endpoint.getComment(), endpoint.getMethodName()),
                "operationId", endpoint.getMethodName(),
                "x-anonymous", endpoint.getMetadata().isAnonymous(),
                "responses", responses("200", "Operação concluída", ref(name + "Output"), false, false)
        );
        if (endpoint.getMetadata().isAnonymous()) operation.put("security", List.of());
        if (endpoint.getPermissions() != null) {
            operation.put("x-permission-resource", endpoint.getPermissions().getResource());
            operation.put("x-permissions", endpoint.getPermissions().getPremissions());
        }
        if ("get".equals(method)) {
            operation.put("parameters", endpointParameters(endpoint.getMetadata().getInput(), project));
        } else {
            operation.put("requestBody", requestBody(ref(name + "Input")));
        }
        @SuppressWarnings("unchecked")
        Map<String, Object> pathItem = (Map<String, Object>) paths.computeIfAbsent(path, ignored -> object());
        pathItem.put(method, operation);
    }

    private static List<Map<String, Object>> endpointParameters(List<Parameters> parameters, Properties project) {
        List<Map<String, Object>> output = new ArrayList<>();
        for (Parameters parameter : parameters) {
            output.add(map(
                    "name", parameter.getParameterName(),
                    "in", "query",
                    "required", true,
                    "schema", parameterSchema(parameter, project)
            ));
        }
        return output;
    }

    private static List<Map<String, Object>> listParameters() {
        return List.of(
                map("name", "size", "in", "query", "schema", map("type", "integer", "minimum", 1, "default", 20)),
                map("name", "offset", "in", "query", "description", "Página baseada em 1 na requisição.", "schema", map("type", "integer", "minimum", 1, "default", 1)),
                map("name", "filter", "in", "query", "description", "Filtro Gonthera: eq, isNull, notNull, gte/ge e lte/le, combinado por and ou or.", "schema", map("type", "string")),
                map("name", "order", "in", "query", "description", "Ordenação no formato campo,asc ou campo,desc.", "schema", map("type", "string")),
                displayFields()
        );
    }

    private static Map<String, Object> displayFields() {
        return map(
                "name", "displayFields", "in", "query",
                "description", "Campos separados por ponto e vírgula; o padrão é *.",
                "schema", map("type", "string", "default", "*")
        );
    }

    private static Map<String, Object> fieldSchema(EntityFields field, Properties project, InputMode mode) {
        Entities related = entity(project, field.getFieldProperties().getFieldType());
        Map<String, Object> schema;
        if (related != null) {
            String suffix;
            if (mode == InputMode.OUTPUT) suffix = "";
            else if (field.getRelationShips() != null && field.getRelationShips().isReference()) suffix = "Reference";
            else suffix = mode == InputMode.UPDATE ? "Update" : "Create";
            schema = ref(className(related.getEntityName()) + suffix);
        } else {
            schema = scalarSchema(field.getFieldProperties().getFieldType(), project);
        }
        if (field.isList()) schema = map("type", "array", "items", schema);
        if (field.getMetadata() != null && field.getMetadata().isNullable()) schema = nullable(schema);
        return schema;
    }

    private static Map<String, Object> nullable(Map<String, Object> schema) {
        if (Boolean.TRUE.equals(schema.get("nullable"))) return schema;
        if (schema.containsKey("$ref")) return map("allOf", List.of(schema), "nullable", true);
        schema.put("nullable", true);
        return schema;
    }

    private static Map<String, Object> parameterSchema(Parameters parameter, Properties project) {
        Map<String, Object> schema = scalarSchema(parameter.getParameterType(), project);
        if (parameter.isList()) return map("type", "array", "items", schema);
        return schema;
    }

    private static Map<String, Object> scalarSchema(String type, Properties project) {
        Enums enumeration = enumeration(project, type);
        if (enumeration != null) return ref(className(enumeration.getEnumName()));
        Entities entity = entity(project, type);
        if (entity != null) return ref(className(entity.getEntityName()));
        switch (type) {
            case "uuid": return map("type", "string", "format", "uuid");
            case "password": return map("type", "string", "format", "password");
            case "datetime": return map("type", "string", "format", "date-time");
            case "date": return map("type", "string", "format", "date");
            case "int":
            case "integer": return map("type", "integer", "format", "int32");
            case "long": return map("oneOf", List.of(map("type", "integer", "format", "int64"), map("type", "string", "pattern", "^-?\\d+$")));
            case "decimal":
            case "double": return map("type", "number", "format", "double");
            case "boolean": return map("type", "boolean");
            case "byte":
            case "byte[]":
            case "inputStream": return map("type", "string", "format", "byte");
            case "map": return map("type", "object", "additionalProperties", true);
            case "requestdata": return map("type", "object");
            case "responsedata": return map("type", "object");
            default: return map("type", "string");
        }
    }

    private static Map<String, Object> responses(String successStatus, String description,
                                                  Map<String, Object> successSchema,
                                                  boolean notFound, boolean conflict) {
        Map<String, Object> responses = object();
        Map<String, Object> success = map("description", description);
        if (successSchema != null) success.put("content", jsonContent(successSchema));
        responses.put(successStatus, success);
        responses.put("400", errorResponse("Requisição inválida"));
        if (notFound) responses.put("404", errorResponse("Registro não encontrado"));
        if (conflict) responses.put("409", errorResponse("Conflito de persistência ou relacionamento"));
        responses.put("500", errorResponse("Erro interno"));
        responses.put("503", errorResponse("Banco de dados indisponível"));
        return responses;
    }

    private static Map<String, Object> requestBody(Map<String, Object> schema) {
        return map("required", true, "content", jsonContent(schema));
    }

    private static Map<String, Object> errorResponse(String description) {
        return map("description", description, "content", jsonContent(ref("Error")));
    }

    private static Map<String, Object> jsonContent(Map<String, Object> schema) {
        return map("application/json", map("schema", schema));
    }

    private static boolean requiredOnCreate(EntityFields field, EntityFields key) {
        if (field == key && autoGeneratedKey(field)) return false;
        if (field.getMetadata() == null || field.getMetadata().isNullable()) return false;
        if (field.isList()) return false;
        if (field.getRelationShips() == null) return true;
        return !field.getRelationShips().isBidirectional();
    }

    private static boolean autoGeneratedKey(EntityFields field) {
        String type = field.getFieldProperties().getFieldType();
        return "uuid".equals(type) || "int".equals(type) || "integer".equals(type);
    }

    private static Entities entity(Properties project, String type) {
        return project.getEntities().stream()
                .filter(value -> value.getEntityName().equals(type))
                .findFirst().orElse(null);
    }

    private static Enums enumeration(Properties project, String type) {
        return project.getEnums().stream()
                .filter(value -> value.getEnumName().equalsIgnoreCase(type))
                .findFirst().orElse(null);
    }

    private static String endpointTag(Endpoints endpoint) {
        return endpoint.getGrouper() == null || endpoint.getGrouper().isBlank()
                ? "Custom" : className(endpoint.getGrouper());
    }

    private static void addDescription(Map<String, Object> schema, String value) {
        if (value != null && !value.isBlank()) schema.put("description", value);
    }

    private static String description(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value;
    }

    private static Map<String, Object> ref(String name) {
        return map("$ref", "#/components/schemas/" + name);
    }

    private static Map<String, Object> object() {
        return new LinkedHashMap<>();
    }

    private static Map<String, Object> map(Object... entries) {
        Map<String, Object> output = object();
        for (int index = 0; index < entries.length; index += 2) {
            output.put((String) entries[index], entries[index + 1]);
        }
        return output;
    }

    private enum InputMode {
        OUTPUT, CREATE, UPDATE, REFERENCE
    }
}
